# Numpy

NumPy library is a linear algebra library which acts as a building block for data science in python.It stands for Numerical Python. NumPy helps to work with Arrays(Used to store mutiple values) which is faster than lists in python.It is called 'ndarray'. NumPy arrays are : vectors and Matrices. vectors are 1D and Matrices are 2D(still ony one row and one column).

# NumPy Arrays

In [3]:
my_numbers=[1,2,3,4,5,6,7,8]

In [4]:
import numpy as np

In [5]:
arr=np.array(my_numbers)

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
arraymat=np.array(my_matrix)

In [9]:
arraymat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(arraymat.ndim)

2


In [11]:
# Range fubction in Numpy (Start,Stop used works same as inclusive,exclusive)
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# For odd range
np.arange(1,11,2)
#For Even range
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#Random Array with uniform distribution of values
np.random.rand(7)

array([0.18961242, 0.43264551, 0.80238674, 0.83876798, 0.7226879 ,
       0.05018574, 0.98260728])

In [19]:
#Random array with Random distribution centred around 0
np.random.randn(5)

array([-0.25927983,  0.92342123, -1.1830372 ,  0.75283512, -0.63010652])

In [20]:
#Random array with Random integers (Inclusive,Exclusive,no of integers)
randomint=np.random.randint(1,101,20)
randomint

array([29, 90, 64, 39, 95, 19, 83, 12, 38, 46, 50, 43, 89, 29, 96, 38, 40,
       97, 32, 51])

In [21]:
#Find Maximum
randomint.max()
#Find Minimum
randomint.min()

12

In [22]:
#To check index of maximum value
randomint.argmax()

17

In [23]:
randomint.dtype

dtype('int32')

In [24]:
randomint.shape

(20,)

# NumPy Index and Select

In [25]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr[5]

6

In [27]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [28]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [29]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [30]:
arrcopy=arr.copy()

In [31]:
arrcopy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arrcopy[3:4]=40

In [33]:
arrcopy

array([ 1,  2,  3, 40,  5,  6,  7,  8,  9, 10])

In [34]:
arr2d=np.array([[15,25,56],[32,45,78],[54,89,90]])
arr2d

array([[15, 25, 56],
       [32, 45, 78],
       [54, 89, 90]])

In [35]:
arr2d[0][1]

25

In [36]:
arr2d[0,1]

25

In [38]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
boolarr=arr>5

In [40]:
boolarr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
arr[boolarr]

array([ 6,  7,  8,  9, 10])

In [43]:
arr[arr<4]

array([1, 2, 3])

In [44]:
arr5dim=np.arange(1,51).reshape(5,10)

In [45]:
arr5dim

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [47]:
arr5dim[2:4,4:6]

array([[25, 26],
       [35, 36]])

# NumPy Operations

In [48]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [52]:
arr+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [53]:
arr*20

array([ 20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

In [54]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [57]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [58]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])